language: python
python:
  - "2.6"
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install: "pip install -r requirements.txt"
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.10
  - DJANGO_VERSION=1.8.4